name: "jina_reranker"
backend: "python"
max_batch_size: 0

input [
  {
    name: "QUERY"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  },
  {
    name: "PASSAGES"
    data_type: TYPE_BYTES
    dims: [ -1 ]
  }
]

output [
  {
    name: "SCORES"
    data_type: TYPE_FP32
    dims: [ -1 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
  }
]
