name: "bi_encoder_ingestion"
backend: "python"

max_batch_size: 128

dynamic_batching {
  preferred_batch_size: [ 2, 4, 8 ]
  max_queue_delay_microseconds: 10000
}

input [
  {
    name: "TEXT"
    data_type: TYPE_STRING
    dims: [ -1 ]
    optional: true
  },
  {
    name: "IMAGE_BASE64"
    data_type: TYPE_STRING
    dims: [ -1 ]
    optional: true
  }
]

output [
  {
    name: "EMBEDDING"
    data_type: TYPE_FP32
    dims: [ 768 ]
  }
]

instance_group [
  {
    count: 1
    kind: KIND_GPU
    gpus: [ 0 ]
    rate_limiter {
      resources [
        {
          name: "GPU_MEMORY"
          count: 4000
        }
      ]
      priority: 1
    }
  }
]
